print("안녕하세요! 다음 질문에 답하고 이야기를 완성하세요.")
print()
animal = input("동물을 입력하세요: ")
name = input("이름을 입력하세요: ")
adjective1 = input("형용사를 입력하세요(OO(이)고): ")
color1 = input("색을 입력하세요(OO색): ")
adjective2 = input("형용사를 입력하세요(OOO니다): ")
noun1 = input("명사를 입력하세요: ")
noun2 = input("명사를 입력하세요: ")
noun3 = input("명사를 입력하세요: ")
adjective3 = input("형용사를 입력하세요(OO은): ")
color2 = input("색을 입력하세요: ")
noun4 = input("명사를 입력하세요: ")

print("다음은 여러분이 만든 이야기입니다.")
print()
print("저의 반려동물은", animal, "이며 이름은", name, "입니다.")
print(adjective1, "(이)고", color1, "이며", adjective2, "니다.")
print(name, "은(는) ",  noun1, ",", noun2, ",", noun3, "을(를) 먹습니다.")
print("가장 좋아하는 장난감은", adjective3, color2, noun4, "입니다.")